### ISSUE TITLE
openning login page blinks a window for few milliseconds before appearing on screen

### ISSUE THREAD

**Issue by adsau59** [fishyboteso/fishyboteso#118]

**Comment by SemjonWilke** [comment]
cant reproduce

**Comment by adsau59** [comment]
I'll post a video, or try to debug it

**Comment by adsau59** [comment]
https://user-images.githubusercontent.com/10076396/177095309-350877e1-b26e-415a-ad27-f07901750972.mp4

Observed: renders after the popup is displayed
Expected: render everything before displaying the login page

Also, it doesn't follow the popup norms (incorrect icon, not centered wrt to fishy gui)

**Comment by SemjonWilke** [comment]
I don't think this is another window and I also don't think, that we can do much about that. It's simply loading slow, because this is some html stuff. The best solution for this and the other problems I have, is rewriting that widget as a tk frame.

This is the first Frame in the video after you started the popup. The white box is completely bound by the popup size. I am sure it is just not loading as fast as the rest of the widget.

![grafik](https://user-images.githubusercontent.com/1882648/177193847-141882fc-03ec-492e-93c7-f2c08b009356.png)

And the second one, everything is fine with this one.

![grafik](https://user-images.githubusercontent.com/1882648/177193895-e42937b9-ca62-43d6-a84c-4eff8f9171be.png)

**Comment by adsau59** [comment]
seems like too much effort for a small issue, tagged it as low priority, we can look into it later on

**Comment by SemjonWilke** [comment]
I'd simply close it and keep it in the far back of my head.

**Comment by adsau59** [comment]
okay closing the issue, with unsolved
